### ISSUE TITLE
Clean up repo for release

### ISSUE THREAD

**Issue by taktran** [Financial-Times/ebi#48]
Follow https://github.com/Financial-Times/next/issues/304

## TODO

* [x] Simplify `bin` field in `package.json`
* [x] Standardise npm scripts
* [x] `.editorconfig` - EditorConfig
* [x] CODEOWNERS
* [x] LICENSE
* [x] Circle ci config for `publish` eg, https://github.com/Financial-Times/tooling-helpers/blob/master/.circleci/config.yml - set up `NPM_AUTH_TOKEN` circle ci for now (in vault)
  * See https://github.com/Financial-Times/next-ci-shared-helpers/blob/master/helper-npm-version-and-publish-public
* [x] Update README with how to run
* [x] Add wiki page for examples
* Consistency chores
  * [x] Rename to `package_engines.js` to `package-engines.js`
  * [x] Use `filepath` instead of `file` for positional arguments

**Comment by taktran** [comment]
Released 🎉 

https://www.npmjs.com/package/ebi
